### ISSUE TITLE
FBI error "Failed to acquire kernel access" 11.0

### ISSUE THREAD

**Issue by GHGJobo** [Steveice10/FBI#172]
Hello,

My O3DS has menuhax and FBI installed. But when i start FBI i get this error:
--------FBI has encountered a fatal error!--------

             Failed to acquire kernel access.

------------Press any button to exit.------------

It runs on 11.0.0-33E

Thanks

**Comment by urherenow** [comment]
Read the other million closed issues on this matter. There IS NO KERNEL ACCESS ON 11.x. You must be running a CFW and running FBI from your home screen on 11.x.

**Comment by 3DSHomeBrewer** [comment]
@Steveice10 Dude! you are genius, you are my mentor cause you are programming geek and you made such a wonderful project and i would also love to use it but actually the problem is i am on firmware 11.0.0 33U on my 2DS, so will you help me out and make an update compatible with my 2DS, Thanks in ADVANCE my Mentor!
