### ISSUE TITLE
issue with installing multiple cias at once

### ISSUE THREAD

**Issue by gh0sti** [Steveice10/FBI#207]
just finished the guide and setup of a9lh and luma cfw. However every time I go to do multiple installs of cia games it crashes the app and 3ds says there something wrong and reboots the device. Can this be looked into and fixed? old 3DS XL latest 11.1 firmware and luma cfw with a9lh

**Comment by dbw-holic** [comment]
Same problem here.

**Comment by miniluigi008** [comment]
@gh0sti @dbw-holic Check to make sure you have enough space before installing cias. I know homebrew doesn't handle running out of space gracefully. You can't completely fill up the SD card and then install them, you'll run out of space because the originals are still there after you have the installed copy. If this is your problem, then you should leave about 4GB for swap space and then select "install and delete."

**Comment by Steveice10** [comment]
Is this still an issue?

**Comment by gh0sti** [comment]
too be honest I wasnt able to test this furthur since I filled up my sd card, I thought i had enough space to intsall a lot of games at once.
