### ISSUE TITLE
Failed to install, Doesn't exist / Failed to open

### ISSUE THREAD

**Issue by Mysarie** [Steveice10/FBI#211]
All CIA's I try to install will progress to 100% then give me this error. This is on a N3DS with Luma CFW and A9LH installed.

Failed to install CIA file.
Result code: 0xC8804478
Level: Status: (25)
Summary: Not found (4)
Module: FS (17)
Desc: Doesn't exist / Failed to open (120)

**Comment by Committee** [comment]
Do you have a Nintendo folder on your sd card?

**Comment by Mysarie** [comment]
I have a "Nintendo 3DS" folder

**Comment by Committee** [comment]
Your FBI is it an inject to H&S? Are you running it through homebrew or cia?

**Comment by Mysarie** [comment]
Its injected into H&S, sorry i should have included that in the OP

**Comment by Kytuzu** [comment]
I have this same situation, as Mysarie said.

**Comment by james-d-elliott** [comment]
Try a different SD card.

**Comment by Steveice10** [comment]
Just to make sure, do you have the usual .db files in "SD:/Nintendo 3DS/(id0)/(id1)/dbs"?

**Comment by Ch0c0bo** [comment]
I'm in the same situation and i don't know what to do about it. I do have import.db and title.db files in dbs.

**Comment by mugwhump** [comment]
Same here. I'm following the Plailect guide to downgrade via system transfer (3DS to N3DS), and the H&S-injected FBI can't install any CIAs (section VI [here](https://3ds.guide/installing-arm9loaderhax) ). I too have import.db and title.db.

The only place I differed from the guide was not copying the full contents of /Nintendo 3DS/id0/id1/title/00040000 from the old SD to the new mSD since that's where all the games were and the new mSD is 4x smaller.

**Comment by urherenow** [comment]
Just for grins, backup both .db files, then delete them, make new blank ones, then go to data management to 'fix' them and try again.

**Comment by mugwhump** [comment]
It worked! More detailed instructions [here](https://www.reddit.com/r/3dshacks/comments/39elie/database_does_not_exist_in_fbi_error/curcvq3/).

Thanks urherenow!

**Comment by Ch0c0bo** [comment]
I confirm that it worked, thanks a lot !

**Comment by Steveice10** [comment]
Not an FBI problem, then. Thanks for finding a solution.
