### ISSUE TITLE
Stability issues when switching from apps

### ISSUE THREAD

**Issue by spcrypt2** [Steveice10/FBI#250]
I find that release 2.4.4 (the one that had the Nintendo logo show while loading) was much more stable when switching from applications. 

To recreate the issue, just open any application (lumaupdater, eShop, etc.) press home, and open FBI. 25% of the time it won't go past the Homebrew screen making a restart necessary. 
I've tried to downgrade to 2.4.4 through a CIA and I end up having the following result:

"Failed to install CIA file.
Result code: 0xD8E08027
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Invalid or outdated title version (39)"

Any reason for these changes, loading change & not being able to downgrade? can we get those back?

**Comment by Steveice10** [comment]
I can't seem to reproduce your issue; either it's been fixed by the latest source or it's a problem specific to you.

The logo was changed as the Nintendo 3DS logo data was cited in the recent DMCA takedown of freeShop, and I'm not willing to take any chances. As for downgrading, that is simply a limitation of how the 3DS title management system works. You should be able to downgrade if you delete FBI from within itself and install it again before closing the app.
