### ISSUE TITLE
New version fbi

### ISSUE THREAD

**Issue by Francesco902** [Steveice10/FBI#317]
New version fbi for 11.3?

**Comment by DerekTheKing** [comment]
PLEASE GOD! PLEASEEE!!

**Comment by dogtopus** [comment]
No

**Comment by MKTerran** [comment]
We need to either get FBI working again somehow. We already have soundhax working so it shouldn't be that hard right? or am I totally wrong here

**Comment by Steveice10** [comment]
Need a new kernel exploit or other method of gaining the required service access. Plus, this is no longer an FBI issue since kernel exploits are now external, like fasthax for example. If a new kernel exploit comes out with an app to add in the kernel backdoor function, it should work without any changes to FBI.

**Comment by Francesco902** [comment]
Thanks for the answers, bye


Il 09/mar/2017 07:03 PM, "Steven Smith" <notifications@github.com> ha
scritto:

**Comment by Paradox355** [comment]
Works just fine on 11.3 for me. Just used it to install homebrew cia today.
