### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by DevShadd** [Steveice10/FBI#386]
I had these issues that have been happening to me on both my N3DS and O3DS on LumaCFW:
►After FBI is opened, when going back to the home menu when pressing start to close the CIA file version, application top screen icons disappear when I hover over them
►After installing an app, it will most likely not be able to open the present nor being able to see the name of the present (quick fix is to press the power button on the system and press home when you get the power confirmation screen, but alternatively you could power off the system and turn it back on)

**Comment by Steveice10** [comment]
* Pressing start to close FBI is mainly intended for the 3DSX version, and is only available in the CIA version because some people find it faster and more convenient. I can't really do anything about the side effects of improperly exiting the app.
* I've never experienced any issues with opening or seeing the names of presents after installing a CIA. Are you sure this isn't some issue with your system or SD card data? Either way, I just pass the CIA file on to Nintendo's AM service for installation; whatever happens afterward is beyond my control.
