### ISSUE TITLE
Suggestion:  Search installed titles by name

### ISSUE THREAD

**Issue by xm915** [Steveice10/FBI#392]
Requesting a search feature for the Installed Titles page.

Being able to search the list of your installed titles by name would be very useful because you can already launch the game from this menu.  

This feature would be great for users with a lot of titles installed.

Thank you for your continued support of an excellent application.

**Comment by xm915** [comment]
After FBI loads list of titles installed, could it write that to a .xml file to be searched for that instance?

Maybe adding a feature to scan for new installed titles, or just quick load the built .xml file from last load.


I have looked through previous requests to see if this has been suggested before, i see a few topics where you had previously addressed this:


----------------------------------------------------------------
----------------------------------------------------------------
https://github.com/Steveice10/FBI/issues/157
----------------------------------------------------------------
 shad00m commented on Jul 11, 2016

Is it possible to add a search or at least sort function in the titles menu?
I'm trying to delete a couple of games I don't like anymore but scrolling takes quite some time as the games are scattered all around
thank you :)

@Steveice10
Owner
Steveice10 commented on Jul 11, 2016 • edited

I currently don't plan to add this. The problem with sorting is that I'd have to actually load all of the information before I can sort it, which would take a long time. Searching would be problematic for the same reason, as things like names wouldn't be available to search until all the information is loaded, and by that time, scrolling is no longer really an issue, as the main problem with scrolling is when things aren't finished loading.

----------------------------------------------------------------

----------------------------------------------------------------
https://github.com/Steveice10/FBI/issues/45
----------------------------------------------------------------
 micah686 commented on Apr 2, 2016

I would like you to add support for loading the names of games from an external file, such as the 3dsdb.com XML list. This would make it a lot easier to find the title in a list of games from the sd card, instead of having to find what titleid coresssponds to what game.

If implemented, it would also be nice to be able to load names of system titles/homebrew from an xml as well, which would make it a lot easier to find the title that you needed.

@Steveice10
Owner
Steveice10 commented on Apr 2, 2016

The rewrite already has support for showing titles from the SMDH, whenever it ends up finished.

----------------------------------------------------------------

**Comment by Steveice10** [comment]
I agree that a search function would be nice, but it would be a bit difficult for me to work into the current codebase, and I don't really have the time or desire to make any more large changes to the FBI code.

Basically, in order to display the search results list, I'd need to either create a new instance of the current list UI with only the results as contents or add a non-permanent filter to the base list UI.

The problem with the first solution is that I'd have to add in special case checks for repopulating, exiting, managing, etc. the list when its a filtered view and not the entire list. Plus, if I wanted to have the search function available in all lists for consistency, I'd have to duplicate this code for every single type of list.

The problem with the second solution is that I need to preserve the original, unfiltered list so that it can be returned to from the search results. A flag could be added to list items to set whether or not they should be visible to the user, however if I did this, rather than working with consecutive list indices, I would have to loop through all items to check the hidden flag each time I wanted to look up an item at a specific user-facing position or advance the cursor to the next visible item. This would make navigation, touch control, etc slower and much more complex.
