### ISSUE TITLE
Error 0xC92044E7 on browsing system save contents

### ISSUE THREAD

**Issue by d0k3** [Steveice10/FBI#403]
There is never a problem browsing the first save I chose, and sometimes I can also browse another one. After looking into a few saves (without even doing anything else), however, I get this screen:
https://ibb.co/h6JEtR

No system saves can be browsed afterwards without restarting FBI in between.

**Comment by Steveice10** [comment]
If opening system save data results in a "Resource Locked" error, it's because another process (i.e. the service the save data belongs to) is running and has a lock on the save data. Not much I can do about that.

Opening other system save data also works fine for me after attempting to open locked data. I'm not able to reproduce the issue you're having with it.
