### ISSUE TITLE
[Optimization] file listing in a directory is too slow

### ISSUE THREAD

**Issue by fraf** [Steveice10/FBI#416]
Approximatively, from 100 or more, file listing in a directory take too much time and blocking I/O operation.
Can you inspire on file listing done by emulators : retroarch rgui , mgba....
They are instantaneous. It's curious that it is so slow : only file title is displayed, no more information.

My "roms" directory is 800 files length.

**Comment by Steveice10** [comment]
If said files are CIA files, it's because it loads the title information for each one to display on the top screen when selected. If this wasn't done ahead of time, scrolling through the list would be much slower.

**Comment by fraf** [comment]
Ok it's right i forgot thé informations displayed on thé upper screen. But Can this be displayed on demand ? 
I don't Care when i am waiting for reaching thé z letter.
Only when i select a file (highlight title), headers are loaded. (The file détails)

**Comment by Steveice10** [comment]
That would probably make scrolling through the list annoyingly slow.

I suppose I could do what I did with the TitleDB listing and load metadata afterwards in the background. I'll reopen this as a reminder for when I can get around to trying it.

**Comment by fraf** [comment]
Good news.
Thinks about emulators like mgba.
Same behavior would be very nice.
They simply list files in a directory, nothing more.
Details should be on demand.
File explorer in a core feature of FBI. It should be fast.
Enjoy new year,
Cheers

**Comment by yoshi314** [comment]
Why not make a cache for metadata of installed files, for faster lookup? If a user is unsure about its validity, there might be an option to rebuild it.

**Comment by fraf** [comment]
According to me, the 99% common user case is : **He don't care about metadata.**
But these informations can be interested for someone. As it is an expensive process for plenty of files, you should implement the "right click->properties on the file". So it implies an "on demand" (one by one) process.
From that supposition, caching these extra information for only one file becomes  optional and maybe unecessary.
Like "delete file" or "copy" or "move" file, you can add "show properties" option.
Do you think you have to enable file listing with metadata directly shown ? Not for me in any case.

**Comment by Steveice10** [comment]
I've finally gotten around to implementing the new behavior in the experimental branch.

Files will be listed first, and only the file extension will be checked to see if they're CIAs/tickets or not, so that you don't have to wait for metadata to load in order to install them. Once all files have been listed, it will then go back and attempt to load metadata for each file marked as a CIA or ticket. If the metadata cannot be loaded, meaning the CIA/ticket is invalid, then the file will be reclassified as a normal file.

**Comment by Steveice10** [comment]
If you'd like to test out the new behavior, here's a build of the latest source as of this post: https://www.dropbox.com/s/lhjq8i1ora4cvt4/FBI.zip?dl=1

Note that this build was made during ongoing development on some core areas of FBI, so it may not otherwise be perfectly stable. I would only recommend using it to test the new behavior and report back how well it works to solve your problem.

**Comment by fraf** [comment]
Sorry for late, link is dead.
