### ISSUE TITLE
Battery icon not displaying true battery life

### ISSUE THREAD

**Issue by pitrako** [Steveice10/FBI#462]
The battery icon displays different battery life in FBI, in my 2DS menu It displays correctly.

**Comment by Steveice10** [comment]
Can you show screenshots? FBI gets the battery level from the 3DS OS.

**Comment by pitrako** [comment]
https://image.ibb.co/hTZhwU/IMG_20180812_214029.jpg

**Comment by Sanaki** [comment]
I'll verify when my battery runs down a bit, but I've noticed some oddities with the system battery indicator since updating to 11.8. I believe the bars now tick away at 80%, 50%, and 20%, with the red charge light coming on at 10% and flashing angrily at 5%. The last bar never disappears. As far as I'm aware, this isn't consistent with the previous indicator tiers. FBI may simply continue using the old tiers despite them changing.

If you want to check for yourself and are using the current release of Luma3DS, Open Rosalina to check battery percentage (default L+down+select).

**Comment by Steveice10** [comment]
I think FBI is actually displaying the right battery level, just with a different representation of each level that doesn't match the home menu. I'll make sure to adjust it for the next release.

**Comment by d0k3** [comment]
Same issue here, and explanation:
https://github.com/d0k3/GodMode9/issues/416

GM9 will keep using the linear battery indicator, btw. It is not designed to do the same thing home menu does.

**Comment by Steveice10** [comment]
I'm getting the current battery level (IIRC) the same way the home menu does, from the 3DS OS. My understanding is that the home menu displays it this way:
* 5 = 4 bars
* 4 = 3 bars
* 3 = 2 bars
* 2 = 1 bar
* 1 = 1 bar, blinking red light
* 0 = 0 bars

FBI, however, displays it this way:
* 5 = 4 blue bars
* 4 = 4 bars
* 3 = 3 bars
* 2 = 2 bars
* 1 = 1 bar
* 0 = 0 bars

I'm planning on letting my battery run down at some point to verify this for certain.

**Comment by Sanaki** [comment]
Been running my 3DS (new 3DS, if relevant) down today, Looks like the system shows three bars at 60%, two bars at 30%. From what I remember it doesn't drop to one bar until 10%. That said, FBI doesn't show three bars until the system is at 30%, so I think you're spot on in terms of what's going on. I'll keep draining it and edit this with confirmation as I hit lower battery levels.

**Comment by Steveice10** [comment]
Should be closed by https://github.com/Steveice10/FBI/commit/26999ae72e16973805986e3895733c1a399153e8
