### ISSUE TITLE
Normally installing cias at 1.8mbps but it drops to a whopping 68kbps at times. Any ideas?

### ISSUE THREAD

**Issue by Mr-Gela** [Steveice10/FBI#472]

**Comment by Steveice10** [comment]
Check your internet connection? I've personally never had this happen.

**Comment by YYoshi241** [comment]
I've had the same issue (o3ds xl with basically same sd but 32gb.)

**Comment by Godigamer69** [comment]
Hi i Have the same issue, sometimes it goes with 1 mbps for hours and sometimes it goes like 60 kbps i don´t know what causes it but now without the freeshop (R.I.P) this is an important issue pls if someone know why this occured pls tell it here. (sorry for my bad english)

**Comment by Bwebeer** [comment]
Hi, i have the same issue, first it start at 1.2 mbps, 5 seconds later it becomes to drop the speed at 39kb/s, ive already used another SD card and it's the same. 
![8414959f-a222-44d5-b408-6ccc8bc60bbf 1](https://user-images.githubusercontent.com/46060255/50369221-f48d4e00-054e-11e9-8caf-61ccec9af1dc.jpg)

**Comment by legoj15** [comment]
I've noticed this with the smash 3ds DLC; because the files are really small, but crazy numerous, write speeds tank, but when I install my streetpass mii plaza DLC cia, it keeps a steady, decent speed, probably due to the fact that its a couple of multi-megabyte files instead of like 60 5 kilobyte files. I don't think there's much that can be done about that
