### ISSUE TITLE
Installing theme package CIAs / GM9 cross-issue

### ISSUE THREAD

**Issue by d0k3** [Steveice10/FBI#479]
This is a cross issue, referencing this GodMode9 issue:
https://github.com/d0k3/GodMode9/issues/438

I already worked with @Ammako to find out more about this issue. What he does is, he builds a CIA for the theme DLC in GodMode9 (title IDs 0004008c00008f00 and 0004008c00008f01). These CIAs contain one purchased theme (I checked, the CIAs look correct).

When reinstalled to the same console, the theme vanishes from the menu. The installation (done by FBI) inside `0:/Nintendo 3DS` looks correct, though. Everything is identical to how it was before (no encryption though, because GM9 standard CIAs are fully unencrypted, thus TMD and CMD don't match competely).

This doesn't have anything to do with the DLC CIA builder fix you did for GodMode9 earlier - we also tried doing the CIA in an earlier GM9 release, with the same result. So, I'm a bit clueless. Also, unsure if this is actually an FBI issue.

On a related note - if the theme DLC CIA is built as a legit CIA in GM9 (that means, with the actual purchased ticket, with encryption intact and the TMD unchanged), FBI fails to install it with error "Cert signature or hash check failed".

**Comment by Ammako** [comment]
To clarify, it doesn't matter which system the CIA is installed to, nor whether there was prior theme DLC already present before installation.

Also, as I've mentioned, I wouldn't be inclined to blame FBI, because DevMenu behaves the same way (and maybe I should have made that clearer, but I only use DevMenu for installing CIAs; installing through FBI was done here for testing purposes just to see if it behaved differently, after already having attempted installing through DevMenu first.)

**Comment by Steveice10** [comment]
Yeah, I don't think this is an FBI issue. FBI doesn't parse the CIA or handle any of its data structures; it just gets passed straight through byte-for-byte to the AM service.

**Comment by Steveice10** [comment]
I'm going to close this for now since it's not an FBI issue, but I'll try to take a look at my own theme data when I have the time, and if I figure anything out I'll chime in on the GodMode9 issue ticket.

**Comment by d0k3** [comment]
Alright. If you need sample data, let me know.
