### ISSUE TITLE
two things

### ISSUE THREAD

**Issue by MAXAITA** [Steveice10/FBI#84]
two things that would help

1. be displayed as default view of the "SD" since most of operations is the installation of cias.

2. to be allowed to leave with the button b instead of the start would help make the operation of output faster.

I congratulate you the best interface.

**Comment by MAXAITA** [comment]
Put the new version I'm waiting for it thanks

**Comment by CrashMan054** [comment]
I prefer the start button for exiting. That way, I don't hit B by accident and close the app.

**Comment by MAXAITA** [comment]
almost always when you're at that point you are already going out

**Comment by Steveice10** [comment]
1. I'd rather the main menu remain the default view, with all the possible sections laid out at the start. It's only one press of the A button to open up the SD menu.

2. It's set to the start button so that people don't accidentally exit while rapidly backing out of menus. If you press start to exit, it's more likely that was your intention than an accidental extra button press.

**Comment by MAXAITA** [comment]
ok thank you
