### ISSUE TITLE
Freeze on ticket install

### ISSUE THREAD

**Issue by aletron** [Steveice10/FBI#96]
when i select to install all tickets, the screen freezes and i have to force shutdown my 3DS

**Comment by deadair3210** [comment]
In my usage, this only happens if there are a lot of tickets in the folder and goes away after a while. Maybe FBI is still parsing the folder, waiting might fix it. In my case, a folder of 1400 tickets causes the dialog to freeze when selecting to install all, but recovers later with the normal dialog

**Comment by Steveice10** [comment]
As mentioned, it's likely just taking time retrieving the ticket information before installation.
